# Generated by Django 2.0.5 on 2019-01-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_shared_room_bed_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared_room',
            name='rent',
            field=models.IntegerField(default=0),
        ),
    ]
