# Generated by Django 2.0.5 on 2019-01-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190101_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared_room',
            name='Area_sqft',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shared_room',
            name='Available',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='shared_room',
            name='Furniture',
            field=models.CharField(choices=[('full', 'full furnished'), ('semi', 'semi furnished'), ('no', 'no furnished')], default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='shared_room',
            name='securitydeposit',
            field=models.IntegerField(default=0),
        ),
    ]
