# Generated by Django 2.0.5 on 2019-01-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20190101_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared_room',
            name='essentialamenities',
            field=models.CharField(choices=[('parking', 'Car parking'), ('security', 'Security services'), ('water', 'Water supply'), ('elevator', 'Elevators'), ('power', 'Power backup'), ('maintenance', '24-hour maintenance')], default='parking', max_length=20),
        ),
    ]
