# Generated by Django 2.0.5 on 2019-01-01 07:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20190101_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared_room',
            name='essentialamenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('parking', 'Car parking'), ('security', 'Security services'), ('water', 'Water supply'), ('elevator', 'Elevators'), ('power', 'Power backup'), ('maintenance', '24-hour maintenance')], default='parking', max_length=49),
        ),
    ]
