# Generated by Django 2.0.5 on 2019-01-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20190102_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_room',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('family', 'family'), ('any', 'any')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='shared_room',
            name='hall',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
        migrations.AddField(
            model_name='shared_room',
            name='kitchen',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
    ]
