# Generated by Django 2.0.5 on 2019-01-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20190102_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_room',
            name='beds_available',
            field=models.IntegerField(default=0),
        ),
    ]
