# Generated by Django 2.0.5 on 2019-01-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20190102_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shared_room',
            old_name='any_description',
            new_name='description',
        ),
    ]
