# Generated by Django 2.0.5 on 2019-01-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20190102_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_room',
            name='user_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
