# Generated by Django 2.0.5 on 2019-01-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_entire_house_entire_house_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entire_house_images',
            old_name='entirehouse',
            new_name='sharedroom',
        ),
    ]
