# Generated by Django 2.0.5 on 2019-03-05 07:22

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_auto_20190102_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image1',
            field=models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)'),
        ),
    ]
