# Generated by Django 2.0.5 on 2019-03-05 17:52

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_question_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_room',
            name='image1',
            field=models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)'),
        ),
        migrations.AddField(
            model_name='shared_room',
            name='image2',
            field=models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)'),
        ),
        migrations.AddField(
            model_name='shared_room',
            name='image3',
            field=models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)'),
        ),
        migrations.AddField(
            model_name='shared_room',
            name='image4',
            field=models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)'),
        ),
        migrations.AddField(
            model_name='shared_room',
            name='image5',
            field=models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)'),
        ),
        migrations.AddField(
            model_name='shared_room',
            name='image6',
            field=models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)'),
        ),
    ]
