# Generated by Django 2.0.5 on 2019-03-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_auto_20190306_0351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entire_house',
            options={'ordering': ['-updated', '-timestamp']},
        ),
    ]
