# Generated by Django 2.0.5 on 2019-03-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_auto_20190306_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='entire_house',
            name='phone',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='private_room',
            name='phone',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='shared_room',
            name='phone',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
